import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing } from '../tokens';

const { width } = Dimensions.get('window');

export const slidableExerciseCardStyles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'visible',
  },
  exerciseCard: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
    height: 110,
    backgroundColor: '#f8f9fa',
    position: 'relative',
  },
  exerciseCardGradient: {
    flexDirection: 'row',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: spacing[12],
    height: 110,
    position: 'relative',
  },
  cardPatternBackground: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 60,
    height: 60,
    opacity: 1.0,
    zIndex: 0,
    borderTopRightRadius: 12,
    overflow: 'hidden',
  },
  cardPatternBackgroundPurple: {
    width: 80,
    right: -10,
  },
  exerciseImageContainer: {
    width: 55,
    height: 110,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    marginRight: spacing[12],
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 1,
  },
  exerciseImage: {
    width: 55,
    height: 110,
  },
  exerciseContent: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingVertical: spacing[2],
    paddingTop: spacing[1],
    zIndex: 1,
  },
  benefitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: spacing[4],
    marginRight: -spacing[4],
  },
  categoryTagContainer: {
    backgroundColor: '#DBEDF4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    alignSelf: 'flex-start',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryTagContainerSmall: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  categoryTagContainerBottomLeft: {
    position: 'absolute',
    bottom: spacing[8],
    left: 75, // 55 (image width) + 12 (margin) = 67 to align with text content
    zIndex: 2,
  },
  categoryTagContainerLarge: {
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  categoryTagText: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Ubuntu-Bold',
    color: '#2B475E',
    textAlign: 'center',
  },
  categoryTagTextLarge: {
    fontSize: 11,
    letterSpacing: 0.3,
  },
  categoryTagTextSmall: {
    fontSize: 9.5,
    letterSpacing: 0.1,
  },
  durationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  durationContainerBottomRight: {
    position: 'absolute',
    bottom: spacing[8],
    right: spacing[8],
    zIndex: 2,
  },
  exerciseDuration: {
    fontSize: 11,
    color: '#001a0e',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    opacity: 0.8,
  },
  exerciseTitle: {
    fontSize: width < 375 ? 16 : 17,
    fontWeight: '700',
    color: '#001a0e',
    lineHeight: width < 375 ? 19 : 21,
    fontFamily: 'Poppins-Bold',
    textShadowColor: 'rgba(255, 255, 255, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    marginBottom: spacing[2],
    marginTop: spacing[6],
    marginRight: spacing[8],
  },
  exerciseDescription: {
    fontSize: 11,
    color: '#002d14',
    lineHeight: 15,
    opacity: 0.9,
    letterSpacing: 0.1,
    marginTop: spacing[0],
    marginRight: spacing[8],
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 12,
    overflow: 'hidden',
  },
  blurView: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[32],
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: spacing[20],
    width: '100%',
    maxWidth: 280,
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#002d14',
    textAlign: 'center',
    marginBottom: spacing[16],
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 22,
  },
  modalButton: {
    width: '100%',
    paddingVertical: spacing[12],
    paddingHorizontal: spacing[16],
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: spacing[8],
    shadowColor: 'rgba(0, 0, 0, 0.08)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  temporaryButton: {
    backgroundColor: '#10B981',
  },
  permanentButton: {
    backgroundColor: '#DC2626',
  },
  cancelButton: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 0,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
  },
  cancelButtonText: {
    color: '#6B7280',
  },
});