import { StyleSheet } from 'react-native';
import { spacing } from '../tokens';

export const slidableHomeExerciseCardStyles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'visible',
  },
  slideTextContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: spacing[8],
    zIndex: 0,
  },
  slideText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#68a9a4',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    opacity: 0.8,
  },
  exerciseCardContainer: {
    position: 'relative',
    marginBottom: spacing[3],
    zIndex: 2,
  },
  checkboxContainer: {
    position: 'absolute',
    top: -25,
    left: -40,
    zIndex: 10,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxContainerFirst: {
    width: 84,
    height: 84,
    left: -40,
    top: -25,
  },
  checkboxContainerSecond: {
    width: 56,
    height: 56,
    left: -40,
    top: -20,
  },
  checkboxContainerThird: {
    width: 42,
    height: 42,
  },
  checkmarkImage: {
    width: 28,
    height: 28,
  },
  checkmarkImageFirst: {
    width: 84,
    height: 84,
  },
  checkmarkImageSecond: {
    width: 56,
    height: 56,
  },
  checkmarkImageThird: {
    width: 42,
    height: 42,
  },
  exerciseCard: {
    backgroundColor: 'transparent',
    minHeight: 75,
  },
  exerciseCardGradient: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: spacing[8],
    paddingLeft: 0,
    marginBottom: spacing[3],
    borderRadius: 20,
    height: 75,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  exerciseCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.components?.cardGap || spacing[12],
    paddingTop: spacing[8],
    paddingBottom: spacing[8],
  },
  exerciseIcon: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 75,
    height: 75,
    overflow: 'hidden',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseIconImage: {
    width: '100%',
    height: '100%',
  },
  exerciseIconImageTest: {
    width: '70%',
    height: '70%',
  },
  exerciseInfo: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 75 + (spacing.components?.cardGap || spacing[12]),
  },
  exerciseName: {
    fontSize: 16,
    color: '#002d14',
    fontWeight: 'bold',
    fontFamily: 'Ubuntu-Light',
    marginBottom: spacing[1],
    textAlign: 'left',
    letterSpacing: -0.3,
  },
  exerciseDescription: {
    fontSize: 13,
    color: '#002d14',
    fontWeight: '400',
    fontFamily: 'Ubuntu-Light',
    lineHeight: 18,
    textAlign: 'left',
    opacity: 0.8,
    letterSpacing: 0.1,
  },
  testButtonsContainer: {
    position: 'absolute',
    left: -40,
    top: '50%',
    transform: [{ translateY: -25 }],
    flexDirection: 'row',
    gap: spacing[4],
  },
  testButtonsContainerFirst: {
    left: -40,
    transform: [{ translateY: -25 }],
  },
  testButtonsContainerSecond: {
    left: -40,
    transform: [{ translateY: -20 }],
  },
  testCheckmarkButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  testCheckmarkButtonFirst: {
    backgroundColor: 'transparent',
  },
  testCheckmarkButtonSecond: {
    backgroundColor: 'transparent',
  },
  testCheckmarkButtonThird: {
    backgroundColor: 'transparent',
  },
  testCheckmarkImage: {
    width: 18,
    height: 18,
  },
  testCheckmarkImageFirst: {
    width: 54,
    height: 54,
  },
  testCheckmarkImageSecond: {
    width: 36,
    height: 36,
  },
  testCheckmarkImageThird: {
    width: 27,
    height: 27,
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    overflow: 'hidden',
  },
  blurView: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[16],
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: spacing[8],
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#002d14',
    textAlign: 'center',
    marginBottom: spacing[8],
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 18,
  },
  modalButtonRow: {
    flexDirection: 'row',
    width: '100%',
    gap: spacing[3],
    marginBottom: spacing[3],
  },
  modalButton: {
    paddingVertical: spacing[6],
    paddingHorizontal: spacing[8],
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  temporaryButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#065f46',
  },
  temporaryButtonText: {
    color: '#065f46',
  },
  permanentButton: {
    flex: 1,
    backgroundColor: '#065f46',
  },
  cancelButton: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginBottom: 0,
    paddingVertical: spacing[4],
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
  },
  cancelButtonText: {
    color: '#6B7280',
  },
});