import { StyleSheet } from 'react-native';
import { spacing } from '../tokens';

export const slidableHomeExerciseCardStyles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'visible',
    marginVertical: 0,
    paddingVertical: 0,
    paddingLeft: 30,
  },
  slideTextContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: spacing[8],
    zIndex: 0,
  },
  slideText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#68a9a4',
    fontFamily: 'Ubunut-Regular',
    textAlign: 'center',
    opacity: 0.8,
  },
  exerciseCardContainer: {
    position: 'relative',
    margin: 0,
    marginTop: -15,
    marginBottom: 5,
    marginLeft: -30,
    padding: 0,
    zIndex: 2,
  },
  timelineContainer: {
    position: 'absolute',
    left: 5,
    top: -15,
    bottom: 0,
    width: 20,
    alignItems: 'center',
    zIndex: 10,
  },
  timelineLineTop: {
    position: 'absolute',
    left: 9,
    top: 0,
    height: 50,
    width: 2,
    backgroundColor: '#9CA3AF',
  },
  timelineLineBottom: {
    position: 'absolute',
    left: 9,
    top: 75,
    bottom: 0,
    width: 2,
    backgroundColor: '#9CA3AF',
  },
  timelineLineBottomLast: {
    backgroundColor: 'transparent',
    borderLeftWidth: 2,
    borderLeftColor: '#9CA3AF',
    borderStyle: 'dashed',
    opacity: 0.5,
    height: 29,
    bottom: 'auto',
  },
  timelineLineBottomLastGradient: {
    position: 'absolute',
    left: 9,
    top: 75,
    width: 2,
    height: 29,
    bottom: 'auto',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  dashSegment: {
    width: 2,
    height: 3,
  },
  dashGap: {
    width: 2,
    height: 2,
  },
  timelineCircle: {
    position: 'absolute',
    top: 55,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#9CA3AF',
    zIndex: 11,
  },
  timelineCircleFirst: {
    top: 50,
    left: -3,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#dccede',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineCircleFirstInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#000000',
    zIndex: 12,
  },
  checkboxContainer: {
    position: 'absolute',
    top: -25,
    left: -40,
    zIndex: 10,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxContainerFirst: {
    width: 84,
    height: 84,
    left: -40,
    top: -25,
  },
  checkboxContainerSecond: {
    width: 56,
    height: 56,
    left: -40,
    top: -20,
  },
  checkboxContainerThird: {
    width: 42,
    height: 42,
  },
  checkmarkImage: {
    width: 28,
    height: 28,
  },
  checkmarkImageFirst: {
    width: 84,
    height: 84,
  },
  checkmarkImageSecond: {
    width: 56,
    height: 56,
  },
  checkmarkImageThird: {
    width: 42,
    height: 42,
  },
  exerciseCard: {
    backgroundColor: 'transparent',
    height: 120,
    margin: 0,
    padding: 0,
  },
  exerciseCardBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    height: 150,
    width: '110%',
    zIndex: 0,
  },
  exerciseCardFullSize: {
    width: '85%',
    height: 120,
    borderRadius: 5,
    alignSelf: 'center',
    marginLeft: 15,
  },
  cardBackgroundShadow: {
    position: 'absolute',
    top: 2,
    left: 2,
    right: 2,
    bottom: -8,
    borderRadius: 20,
    zIndex: -1,
  },
  textOverlay: {
    position: 'absolute',
    top: 35,
    left: 65,
    right: 20,
    zIndex: 2,
  },
  exerciseCardGradient: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: spacing[8],
    paddingLeft: 0,
    marginBottom: 0,
    borderRadius: 20,
    height: 180,
    backgroundColor: 'transparent',
    position: 'relative',
    zIndex: 1,
  },
  exerciseCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.components?.cardGap || spacing[2],
    paddingTop: spacing[2],
    paddingBottom: spacing[2],
  },
  exerciseIcon: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 75,
    height: 75,
    overflow: 'hidden',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseIconImage: {
    width: '100%',
    height: '100%',
  },
  exerciseIconImageTest: {
    width: '70%',
    height: '70%',
  },
  exerciseInfo: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 75 + (spacing.components?.cardGap || spacing[12]),
  },
  exerciseName: {
    fontSize: 17.5,
    color: '#002d14',
    fontWeight: 'bold',
    fontFamily: 'Ubuntu-Light',
    marginBottom: spacing[1],
    textAlign: 'left',
    letterSpacing: -0.3,
  },
  exerciseDescription: {
    fontSize: 13,
    color: '#002d14',
    fontWeight: '400',
    fontFamily: 'Ubuntu-Light',
    lineHeight: 18,
    textAlign: 'left',
    opacity: 0.8,
    letterSpacing: 0.1,
    maxWidth: '85%',
  },
  testButtonsContainer: {
    position: 'absolute',
    left: -40,
    top: '50%',
    transform: [{ translateY: -25 }],
    flexDirection: 'row',
    gap: spacing[4],
  },
  testButtonsContainerFirst: {
    left: -40,
    transform: [{ translateY: -25 }],
  },
  testButtonsContainerSecond: {
    left: -40,
    transform: [{ translateY: -20 }],
  },
  testCheckmarkButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  testCheckmarkButtonFirst: {
    backgroundColor: 'transparent',
  },
  testCheckmarkButtonSecond: {
    backgroundColor: 'transparent',
  },
  testCheckmarkButtonThird: {
    backgroundColor: 'transparent',
  },
  testCheckmarkImage: {
    width: 18,
    height: 18,
  },
  testCheckmarkImageFirst: {
    width: 54,
    height: 54,
  },
  testCheckmarkImageSecond: {
    width: 36,
    height: 36,
  },
  testCheckmarkImageThird: {
    width: 27,
    height: 27,
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    overflow: 'hidden',
  },
  blurView: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[16],
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: spacing[8],
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#002d14',
    textAlign: 'center',
    marginBottom: spacing[8],
    fontFamily: 'Ubuntu-Regular',
    lineHeight: 18,
  },
  modalButtonRow: {
    flexDirection: 'row',
    width: '100%',
    gap: spacing[3],
    marginBottom: 0,
  },
  modalButton: {
    paddingVertical: spacing[6],
    paddingHorizontal: spacing[8],
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  temporaryButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#065f46',
  },
  temporaryButtonText: {
    color: '#065f46',
  },
  permanentButton: {
    flex: 1,
    backgroundColor: '#065f46',
  },
  cancelButton: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginBottom: 0,
    paddingVertical: spacing[4],
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Ubunutu-Regular',
  },
  cancelButtonText: {
    color: '#6B7280',
  },
});