import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing } from '../tokens';

const { width } = Dimensions.get('window');

export const slidableExerciseCardStyles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'visible',
  },
  exerciseCard: {
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
    height: 110,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  exerciseCardContainer: {
    position: 'relative',
    height: 110,
  },
  exerciseCardBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: 110,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  exerciseCardGradient: {
    flexDirection: 'row',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: spacing[12],
    height: 110,
    position: 'relative',
    zIndex: 1,
  },
  exerciseImageContainer: {
    width: 55,
    height: 110,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    marginRight: spacing[12],
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  exerciseImage: {
    width: 55,
    height: 110,
  },
  exerciseContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingVertical: spacing[4],
  },
  tagAndTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[6],
  },
  categoryTagImageContainer: {
    position: 'relative',
    alignSelf: 'flex-start',
    marginBottom: 0,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryTagImage: {
    width: 85,
    height: 28,
    borderRadius: 14,
  },
  categoryTagTextOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Ubuntu-Bold',
    color: '#0A2A0D',
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 28,
  },
  categoryTagImageLarge: {
    width: 110,
    height: 28,
  },
  categoryTagTextOverlayLarge: {
    fontSize: 11,
    letterSpacing: 0.3,
    lineHeight: 28,
  },
  durationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[4],
  },
  exerciseDuration: {
    fontSize: 11,
    color: '#001a0e',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    opacity: 0.8,
  },
  exerciseTitle: {
    fontSize: width < 375 ? 14 : 15,
    fontWeight: '700',
    color: '#001a0e',
    lineHeight: width < 375 ? 17 : 20,
    fontFamily: 'Poppins-Bold',
    textShadowColor: 'rgba(255, 255, 255, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    marginBottom: spacing[2],
  },
  exerciseDescription: {
    fontSize: 13,
    color: '#002d14',
    lineHeight: 17,
    opacity: 0.9,
    letterSpacing: 0.1,
    marginTop: spacing[1],
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
  },
  blurView: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[32],
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: spacing[20],
    width: '100%',
    maxWidth: 280,
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#002d14',
    textAlign: 'center',
    marginBottom: spacing[16],
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 22,
  },
  modalButton: {
    width: '100%',
    paddingVertical: spacing[12],
    paddingHorizontal: spacing[16],
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: spacing[8],
    shadowColor: 'rgba(0, 0, 0, 0.08)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  temporaryButton: {
    backgroundColor: '#10B981',
  },
  permanentButton: {
    backgroundColor: '#DC2626',
  },
  cancelButton: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 0,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
  },
  cancelButtonText: {
    color: '#6B7280',
  },
});